apiVersion: apps/v1 
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 2 
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask
        image: soms1234/flask-app-image:latest
        ports:
        - containerPort: 5000
---

# service file 

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 5000 # pod port
      nodePort: 32007 # port to access externally
